---
{
   "kind": "pipeline",
   "name": "python:3.10,django>=4.2,<4.3",
   "platform": {
      "arch": "amd64",
      "os": "linux"
   },
   "services": [
      {
         "command": [
            "--character-set-server=utf8mb4",
            "--collation-server=utf8mb4_unicode_ci",
            "--default-storage-engine=InnoDB"
         ],
         "environment": {
            "MYSQL_DATABASE": "test_db",
            "MYSQL_PASSWORD": "silver",
            "MYSQL_ROOT_PASSWORD": "secret",
            "MYSQL_USER": "silver"
         },
         "image": "mysql:8.0",
         "name": "mysql",
         "pull": "if-not-exists"
      },
      {
         "image": "redis:3-alpine",
         "name": "redis",
         "pull": "if-not-exists"
      }
   ],
   "steps": [
      {
         "commands": [
            "make dependencies",
            "pip install -U \"django>=4.2,<4.3\"",
            "mkdir /var/log/silver",
            "make lint",
            "make test"
         ],
         "environment": {
            "SILVER_DB_URL": "mysql://silver:silver@mysql/db"
         },
         "image": "python:3.10",
         "name": "test",
         "pull": "always",
         "settings": {
            "group": "build"
         }
      },
      {
         "image": "plugins/docker",
         "name": "publish-docker",
         "pull": "if-not-exists",
         "settings": {
            "force_tag": true,
            "group": "publish",
            "password": {
               "from_secret": "DOCKERHUB_CONFIG_JSON"
            },
            "repo": "presslabs/silver",
            "tags": [
               "${DRONE_BRANCH/master/latest}",
               "${DRONE_COMMIT_SHA:0:7}"
            ],
            "username": "_json_key"
         },
         "when": {
            "branch": [
               "master"
            ],
            "event": [
               "push",
               "tag"
            ]
         }
      },
      {
         "environment": {
            "DRONE_TOKEN": {
               "from_secret": "DRONE_TOKEN"
            }
         },
         "image": "plugins/downstream",
         "name": "trigger-docs-build",
         "pull": "if-not-exists",
         "settings": {
            "fork": true,
            "repositories": [
               "presslabs/docs"
            ],
            "server": "https://drone.presslabs.net"
         },
         "when": {
            "branch": [
               "master"
            ],
            "event": [
               "push"
            ]
         }
      }
   ]
}
---
{
   "kind": "pipeline",
   "name": "python:3.11,django>=4.2,<4.3",
   "platform": {
      "arch": "amd64",
      "os": "linux"
   },
   "services": [
      {
         "command": [
            "--character-set-server=utf8mb4",
            "--collation-server=utf8mb4_unicode_ci",
            "--default-storage-engine=InnoDB"
         ],
         "environment": {
            "MYSQL_DATABASE": "test_db",
            "MYSQL_PASSWORD": "silver",
            "MYSQL_ROOT_PASSWORD": "secret",
            "MYSQL_USER": "silver"
         },
         "image": "mysql:8.0",
         "name": "mysql",
         "pull": "if-not-exists"
      },
      {
         "image": "redis:3-alpine",
         "name": "redis",
         "pull": "if-not-exists"
      }
   ],
   "steps": [
      {
         "commands": [
            "make dependencies",
            "pip install -U \"django>=4.2,<4.3\"",
            "mkdir /var/log/silver",
            "make lint",
            "make test"
         ],
         "environment": {
            "SILVER_DB_URL": "mysql://silver:silver@mysql/db"
         },
         "image": "python:3.11",
         "name": "test",
         "pull": "always",
         "settings": {
            "group": "build"
         }
      },
      {
         "image": "plugins/docker",
         "name": "publish-docker",
         "pull": "if-not-exists",
         "settings": {
            "force_tag": true,
            "group": "publish",
            "password": {
               "from_secret": "DOCKERHUB_CONFIG_JSON"
            },
            "repo": "presslabs/silver",
            "tags": [
               "${DRONE_BRANCH/master/latest}",
               "${DRONE_COMMIT_SHA:0:7}"
            ],
            "username": "_json_key"
         },
         "when": {
            "branch": [
               "master"
            ],
            "event": [
               "push",
               "tag"
            ]
         }
      },
      {
         "environment": {
            "DRONE_TOKEN": {
               "from_secret": "DRONE_TOKEN"
            }
         },
         "image": "plugins/downstream",
         "name": "trigger-docs-build",
         "pull": "if-not-exists",
         "settings": {
            "fork": true,
            "repositories": [
               "presslabs/docs"
            ],
            "server": "https://drone.presslabs.net"
         },
         "when": {
            "branch": [
               "master"
            ],
            "event": [
               "push"
            ]
         }
      }
   ]
}
---
{
   "kind": "pipeline",
   "name": "python:3.10,django>=3.2,<3.3",
   "platform": {
      "arch": "amd64",
      "os": "linux"
   },
   "services": [
      {
         "command": [
            "--character-set-server=utf8mb4",
            "--collation-server=utf8mb4_unicode_ci",
            "--default-storage-engine=InnoDB"
         ],
         "environment": {
            "MYSQL_DATABASE": "test_db",
            "MYSQL_PASSWORD": "silver",
            "MYSQL_ROOT_PASSWORD": "secret",
            "MYSQL_USER": "silver"
         },
         "image": "mysql:8.0",
         "name": "mysql",
         "pull": "if-not-exists"
      },
      {
         "image": "redis:3-alpine",
         "name": "redis",
         "pull": "if-not-exists"
      }
   ],
   "steps": [
      {
         "commands": [
            "make dependencies",
            "pip install -U \"Django>=3.2,<3.3\"",
            "mkdir /var/log/silver",
            "make lint",
            "make test"
         ],
         "environment": {
            "SILVER_DB_URL": "mysql://silver:silver@mysql/db"
         },
         "image": "python:3.10",
         "name": "test",
         "pull": "always",
         "settings": {
            "group": "build"
         }
      },
      {
         "image": "plugins/docker",
         "name": "publish-docker",
         "pull": "if-not-exists",
         "settings": {
            "force_tag": true,
            "group": "publish",
            "password": {
               "from_secret": "DOCKERHUB_CONFIG_JSON"
            },
            "repo": "presslabs/silver",
            "tags": [
               "${DRONE_BRANCH/master/latest}",
               "${DRONE_COMMIT_SHA:0:7}"
            ],
            "username": "_json_key"
         },
         "when": {
            "branch": [
               "master"
            ],
            "event": [
               "push",
               "tag"
            ]
         }
      },
      {
         "environment": {
            "DRONE_TOKEN": {
               "from_secret": "DRONE_TOKEN"
            }
         },
         "image": "plugins/downstream",
         "name": "trigger-docs-build",
         "pull": "if-not-exists",
         "settings": {
            "fork": true,
            "repositories": [
               "presslabs/docs"
            ],
            "server": "https://drone.presslabs.net"
         },
         "when": {
            "branch": [
               "master"
            ],
            "event": [
               "push"
            ]
         }
      }
   ]
}
---
{
   "kind": "pipeline",
   "name": "python:3.11,django>=3.2,<3.3",
   "platform": {
      "arch": "amd64",
      "os": "linux"
   },
   "services": [
      {
         "command": [
            "--character-set-server=utf8mb4",
            "--collation-server=utf8mb4_unicode_ci",
            "--default-storage-engine=InnoDB"
         ],
         "environment": {
            "MYSQL_DATABASE": "test_db",
            "MYSQL_PASSWORD": "silver",
            "MYSQL_ROOT_PASSWORD": "secret",
            "MYSQL_USER": "silver"
         },
         "image": "mysql:8.0",
         "name": "mysql",
         "pull": "if-not-exists"
      },
      {
         "image": "redis:3-alpine",
         "name": "redis",
         "pull": "if-not-exists"
      }
   ],
   "steps": [
      {
         "commands": [
            "make dependencies",
            "pip install -U \"Django>=3.2,<3.3\"",
            "mkdir /var/log/silver",
            "make lint",
            "make test"
         ],
         "environment": {
            "SILVER_DB_URL": "mysql://silver:silver@mysql/db"
         },
         "image": "python:3.11",
         "name": "test",
         "pull": "always",
         "settings": {
            "group": "build"
         }
      },
      {
         "image": "plugins/docker",
         "name": "publish-docker",
         "pull": "if-not-exists",
         "settings": {
            "force_tag": true,
            "group": "publish",
            "password": {
               "from_secret": "DOCKERHUB_CONFIG_JSON"
            },
            "repo": "presslabs/silver",
            "tags": [
               "${DRONE_BRANCH/master/latest}",
               "${DRONE_COMMIT_SHA:0:7}"
            ],
            "username": "_json_key"
         },
         "when": {
            "branch": [
               "master"
            ],
            "event": [
               "push",
               "tag"
            ]
         }
      },
      {
         "environment": {
            "DRONE_TOKEN": {
               "from_secret": "DRONE_TOKEN"
            }
         },
         "image": "plugins/downstream",
         "name": "trigger-docs-build",
         "pull": "if-not-exists",
         "settings": {
            "fork": true,
            "repositories": [
               "presslabs/docs"
            ],
            "server": "https://drone.presslabs.net"
         },
         "when": {
            "branch": [
               "master"
            ],
            "event": [
               "push"
            ]
         }
      }
   ]
}
---
kind: signature
hmac: 1231c01a60b201851df1d8bb5856897afcbde610438a08a84aa6321a58e7452a

...
