pipeline:
  test:
    image: python:${PYTHON_VERSION}
    pull: true
    group: build
    environment:
      - SILVER_DB_ENGINE=django.db.backends.mysql
      - SILVER_DB_NAME=test_db
      - SILVER_DB_HOST=mysql
      - SILVER_DB_USER=silver
      - SILVER_DB_PASSWORD=silver
    commands:
      - make dependencies
      - pip install -U "Django${DJANGO_VERSION}"
      - mkdir /var/log/silver
      - make lint
      - make test

  publish-docker:
    image: plugins/docker
    group: publish
    repo: presslabs/silver
    tags: ["${DRONE_BRANCH/master/latest}", "${DRONE_COMMIT_SHA:0:7}"]
    force_tag: true
    secrets:
      - DOCKER_USERNAME
      - DOCKER_PASSWORD
    when:
      event: [push, tag]

services:
  mysql:
    image: mysql:5.5
    environment:
      - MYSQL_DATABASE=test_db
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=silver
      - MYSQL_PASSWORD=silver
  redis:
    image: redis:3-alpine

matrix:
  DJANGO_VERSION:
    - <2.0
  PYTHON_VERSION:
    - 2.7
    - 3.6
