# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silver', '0044_auto_20171115_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
