# Generated by Django 3.2.13 on 2022-07-22 10:50

from django.db import migrations, models
from django.db.models import F


def plan_amount_update_amount_for_interval_count_gt_1(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    Plan = apps.get_model('silver', 'Plan')
    Plan.objects.using(db_alias)\
        .filter(interval_count__gt=1)\
        .update(amount=F('amount') * F('interval_count'))


def plan_reverse_amount_update_amount_for_interval_count_gt_1(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    Plan = apps.get_model('silver', 'Plan')
    Plan.objects.using(db_alias)\
        .filter(interval_count__gt=1)\
        .update(amount=F('amount') / F('interval_count'))


class Migration(migrations.Migration):

    dependencies = [
        ('silver', '0057_auto_20220720_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='separate_plan_entries_per_base_interval',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('inherit', 'Inherit')], default='inherit', help_text='If not disabled, this will cause the plan entries to be separated by the base interval. For example a plan with interval=month, interval_count=3, will cause the entries to be split by each month, resulting in 3 entries with ', max_length=16),
        ),
        migrations.AlterField(
            model_name='plan',
            name='prebill_plan',
            field=models.BooleanField(help_text='If this is set to True, then the plan base amount will be billed at the beginning of the billing cycle rather than after the end.', null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='only_bill_metered_features_with_base_amount',
            field=models.BooleanField(default=False,
                                      help_text="When set to True, Metered Features will only be billed when the base plan's amount is billed. For example, for a plan with interval=month, interval_count=3, metered features will only be billed every 3 months, along with the base amount."),
        ),
        migrations.RunPython(plan_amount_update_amount_for_interval_count_gt_1,
                             plan_reverse_amount_update_amount_for_interval_count_gt_1),

    ]
