# Generated by Django 3.2.23 on 2024-07-03 11:16

from django.db import migrations, models
from django.db.models import F, Case, When


def migrate_from_bonus_state_to_enabled(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    Bonus = apps.get_model('silver', 'Bonus')
    Bonus.objects.using(db_alias).filter(state='inactive').update(enabled=False)


def migrate_from_bonus_enabled_to_state(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    Bonus = apps.get_model('silver', 'Bonus')
    Bonus.objects.using(db_alias).filter(enabled=False).update(state="inactive")


def migrate_from_discount_state_to_enabled(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    Discount = apps.get_model('silver', 'Discount')
    Discount.objects.using(db_alias).filter(state='inactive').update(enabled=False)


def migrate_from_discount_enabled_to_state(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    Discount = apps.get_model('silver', 'Discount')
    Discount.objects.using(db_alias).filter(enabled=False).update(state="inactive")


class Migration(migrations.Migration):

    dependencies = [
        ('silver', '0061_auto_20230808_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Can be used to easily toggle bonuses on or off.'),
        ),
        migrations.RunPython(
            migrate_from_bonus_state_to_enabled,
            migrate_from_bonus_enabled_to_state
        ),
        migrations.RemoveField(
            model_name='bonus',
            name='state',
        ),
        migrations.AddField(
            model_name='discount',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Can be used to easily toggle discounts on or off.'),
        ),
        migrations.RunPython(
            migrate_from_discount_state_to_enabled,
            migrate_from_discount_enabled_to_state
        ),
        migrations.RemoveField(
            model_name='discount',
            name='state',
        ),
    ]
