# Generated by Django 3.2.23 on 2024-08-07 12:47

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silver', '0062_auto_20240703_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='customers',
            new_name='filter_customers'
        ),
        migrations.RenameField(
            model_name='discount',
            old_name='plans',
            new_name='filter_plans'
        ),
        migrations.RenameField(
            model_name='discount',
            old_name='subscriptions',
            new_name='filter_subscriptions'
        ),
        migrations.AddField(
            model_name='discount',
            name='filter_product_codes',
            field=models.ManyToManyField(blank=True, related_name='filtering_discounts', to='silver.ProductCode'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='end_date',
            field=models.DateField(blank=True, help_text="When set, the bonus will only apply to entries with a greater or equal end_date. Otherwise, a prorated bonus may still apply, but only if the entries start_date is lower than the bonus's end_date.", null=True),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='start_date',
            field=models.DateField(blank=True, help_text="When set, the bonus will only apply to entries with a lower or equal start_date. Otherwise, a prorated bonus may still apply, but only if the entries end_date is greater than the bonus's start_date.", null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='filter_customers',
            field=models.ManyToManyField(blank=True, related_name='filtering_discounts', to='silver.Customer'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='filter_plans',
            field=models.ManyToManyField(blank=True, related_name='filtering_discounts', to='silver.Plan'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='filter_subscriptions',
            field=models.ManyToManyField(blank=True, related_name='filtering_discounts', to='silver.Subscription'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='meta',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder,
                                   null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='meta',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder,
                                   null=True),
        ),
        migrations.AddField(
            model_name='meteredfeature',
            name='meta',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder,
                                   null=True),
        ),
    ]
